node/Cargo.lock
node/actors/consensus/src/leader/replica_commit.rs
node/actors/consensus/src/leader/replica_prepare.rs
node/actors/consensus/src/replica/leader_commit.rs
node/actors/consensus/src/replica/leader_prepare.rs
node/actors/network/src/consensus/handshake/mod.rs
node/actors/network/src/gossip/handshake/mod.rs
node/actors/network/src/io.rs
node/actors/network/src/mux/mod.rs
node/actors/network/src/mux/transient_stream.rs
node/actors/sync_blocks/Cargo.toml
node/actors/sync_blocks/src/peers/mod.rs
node/actors/sync_blocks/src/peers/tests.rs
node/libs/concurrency/src/ctx/channel.rs
node/libs/concurrency/src/ctx/mod.rs
node/libs/concurrency/src/ctx/tests.rs
node/libs/concurrency/src/scope/task.rs
node/libs/concurrency/src/sync/mod.rs
node/libs/crypto/src/bls12_381/mod.rs
node/libs/crypto/src/ed25519/mod.rs
node/libs/roles/src/node/keys.rs
node/libs/roles/src/node/messages.rs
node/libs/roles/src/validator/messages/consensus.rs
node/libs/roles/src/validator/messages/msg.rs
node/libs/storage/src/types.rs
node/libs/utils/src/enum_util.rs

- Improve formatting of errors defined using `thiserror::Error` macro.
- Use strongly typed errors for block validation.
Improves code style; makes it possible to test errors without relying on their messages.

chore: Improve error definitions

---

node/actors/network/src/gossip/tests.rs

Fixes a race condition in `getting_blocks_from_peers` test.
Bugs are bad.

fix: Fix race condition in network tests

---

node/Cargo.lock
node/Cargo.toml
node/actors/executor/Cargo.toml
node/actors/executor/src/lib.rs
node/actors/executor/src/testonly.rs
node/actors/executor/src/tests.rs
node/actors/network/Cargo.toml
node/actors/network/src/consensus/tests.rs
node/actors/network/src/gossip/runner.rs
node/actors/network/src/gossip/tests.rs
node/actors/network/src/testonly.rs
node/actors/network/src/tests.rs
node/actors/sync_blocks/src/lib.rs
node/actors/sync_blocks/src/message_handler.rs
node/actors/sync_blocks/src/peers/mod.rs
node/actors/sync_blocks/src/peers/tests.rs
node/actors/sync_blocks/src/tests/end_to_end.rs
node/libs/concurrency/src/net/tcp/testonly.rs
node/libs/crypto/src/bn254/tests.rs
node/libs/crypto/src/sha256/mod.rs
node/libs/roles/src/validator/messages/block.rs

- Simplifies generating executor configurations.
- Adds byte conversions for `BlockHeaderHash`.
- Makes `SyncBlocks` actor terminate successfully on context cancellation.
Part of preparations for the integration with the server codebase.

feat: Minor extensions for server interoperability

---

node/libs/concurrency/src/ctx/mod.rs

Makes `Ctx::wait()` public, so that it can be used by concurrency crate users.
This will provide a conventional way to wait for a cancel-safe future or context cancellation.

feat: Make `Ctx::wait()` public

---

node/Cargo.lock
node/Cargo.toml
node/libs/protobuf/build.rs
node/libs/protobuf_build/Cargo.toml
node/libs/protobuf_build/src/canonical.rs
node/libs/protobuf_build/src/lib.rs
node/libs/protobuf_build/src/syntax.rs
node/libs/schema/build.rs

Performs minor cleanup for the protobuf_buildcrate, such as using more intelligent local variable names and relying more on `syn` types.
Improves maintainability.

refactor: Minor `protobuf_build` chores

---

node/Cargo.lock
node/actors/executor/src/config/mod.rs
node/actors/executor/src/lib.rs
node/actors/executor/src/tests.rs
node/actors/sync_blocks/src/peers/mod.rs
node/actors/sync_blocks/src/peers/tests/fakes.rs
node/libs/roles/Cargo.toml
node/libs/roles/src/validator/keys/aggregate_signature.rs
node/libs/roles/src/validator/messages/block.rs
node/libs/roles/src/validator/mod.rs
node/tools/src/main.rs

Validate genesis block self-consistency and correspondence to storage when an `Executor` is created.
Allows not to accidentally break a node due to misconfiguration.

feat: Validate genesis block in executor config

---

node/actors/bft/src/inner.rs
node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/leader/state_machine.rs
node/actors/bft/src/leader/tests.rs
node/actors/bft/src/lib.rs
node/actors/bft/src/replica/leader_prepare.rs
node/actors/bft/src/replica/new_view.rs
node/actors/bft/src/replica/state_machine.rs
node/actors/bft/src/replica/tests.rs
node/actors/bft/src/testonly/make.rs
node/actors/bft/src/testonly/run.rs
node/actors/executor/src/config/mod.rs
node/actors/executor/src/config/proto/mod.proto
node/actors/executor/src/config/tests.rs
node/actors/executor/src/lib.rs
node/actors/executor/src/testonly.rs
node/actors/executor/src/tests.rs
node/actors/sync_blocks/src/tests/mod.rs
node/libs/protobuf_build/src/lib.rs
node/libs/roles/src/validator/messages/consensus.rs
node/libs/roles/src/validator/testonly.rs
node/libs/storage/src/tests/mod.rs
node/libs/storage/src/tests/rocksdb.rs
node/tools/src/bin/localnet_config.rs

Allows configuring protocol version for consensus messages instead of hard-coding it.
We intend to use the same protocol version as for the server, which makes hard-coding it not feasible for consensus–server integration.

feat: Allow configuring protocol version

---

node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/leader/tests.rs
node/actors/bft/src/testonly/ut_harness.rs

Add validation for messages sent by replica to have their signer be in the validator set. 
* A new error type variant has been added to the 2 message types.
* Validation has been introduced at the beginning of the processing of each message.
* 2 tests have been added:
* `replica_prepare_non_validator_signer`
* `replica_commit_non_validator_signer`

Validate signer to be in validator set (BFT-384)

---

node/actors/bft/src/inner.rs
node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/lib.rs
node/actors/bft/src/replica/leader_commit.rs
node/actors/bft/src/replica/leader_prepare.rs
node/actors/bft/src/replica/new_view.rs
node/actors/bft/src/testonly/make.rs
node/actors/bft/src/testonly/run.rs
node/actors/bft/src/testonly/ut_harness.rs
node/actors/executor/src/config/mod.rs
node/actors/executor/src/config/proto/mod.proto
node/actors/executor/src/config/tests.rs
node/actors/executor/src/lib.rs
node/actors/executor/src/testonly.rs
node/actors/executor/src/tests.rs
node/tools/src/bin/localnet_config.rs

Removed protocol_version from config.
Instead, I've added a constant in bft crate indicating the version of the protocol implementation.
The payload format should be versioned separately. Payload format version should be included in the payload itself (set via PayloadSource::propose, verified via WriteBlockStore::verify_payload).
What is being versioned is actually the implementation of the consensus, so it doesn't make sense to configure it via config. If it was configurable the implementation wouldn't be able to reason about the protocol version and compatibility of the peers.

Removed protocol_version from config

---

.github/workflows/protobuf_conformance.yaml
node/Cargo.lock
node/Cargo.toml

Put full hash into Cargo.toml for deps.
cargo is not smart enough to deduplicate deps specified by different lengths of the hash prefixes. It is particularly bad for vise which specifies global variables and therefore metrics get registered to different locations.

put full hash into Cargo.toml for deps

---

node/Cargo.lock
node/Cargo.toml
node/deny.toml

Bumps the git revision of `vise` crates.
Necessary for [the similar PR in the main repo](https://github.com/matter-labs/zksync-era/pull/727) to work correctly.

chore: Update `vise` revision

---

node/Cargo.lock
node/libs/protobuf/src/serde.rs
node/tools/Cargo.toml
node/tools/src/config.rs
node/tools/src/lib.rs
node/tools/src/main.rs

Adds a `--seed` command line argument to support seed peer address and key injection when starting the node
Example:
```
executor --seed 10.123.12.21:3043,node:public:ed25519:3059a9ae1de665f2e5dfcb64d5d3a044b2b3617436ddd56c2baf896878b13961 --seed 10.23.22.0:1010,node:public:ed25519:07928c09f2828cbbe1bacc9dc00271c4517c3af1dad034054591e6af10450338
```
will add two IP and key tuples to the `gossipStaticOutbound` in the `config.json` file when starting the node (and it will override the address if the same key is present in the file).
This will be necessary for the test framework to be able to start nodes within a k8s cluster when initially the IP addresses assigned are unknown. In that sense, we will deploy an initial set of Seed Peers, retrieve their IP addresses and then deploy the rest of …

Added `--seed` cli argument to provide IP address, port and key of seed peers on startup

---

node/libs/protobuf/src/lib.rs
node/libs/protobuf/src/repr.rs
node/libs/protobuf/src/testonly/gen_value.rs
node/libs/protobuf/src/testonly/mod.rs

Relocating ~`ProtoRepr`~ the following types and utils from `zksync_protobuf_config` ([zksync-era](https://github.com/matter-labs/zksync-era)) into `zksync_protobuf` ([era-consensus](https://github.com/matter-labs/era-consensus)). This PR just adds them to the new location.   
* trait `ProtoRepr`
* fn `read_required_repr`
* fn `encode<P: ProtoRepr>`
* fn `decode<P: ProtoRepr>`
* trait `RandomValue`
* struct `GenValue`
To make them usable as a shared utility.

refactor(protobuf): relocate types from `zksync_protobuf_config` (BFT-407)

---

.github/workflows/typos.yaml
_typos.toml
node/actors/network/src/noise/stream.rs
node/actors/sync_blocks/src/peers/tests/basics.rs
node/actors/sync_blocks/src/peers/tests/multiple_peers.rs
node/libs/concurrency/src/ctx/channel.rs
node/libs/concurrency/src/net/tcp/listener_addr.rs
node/libs/concurrency/src/scope/state.rs
node/libs/protobuf/src/proto_fmt.rs
node/libs/roles/src/validator/messages/block.rs
node/tools/README.md
node/tools/src/k8s.rs
node/tools/src/rpc/methods/last_committed_block.rs
node/tools/src/rpc/methods/mod.rs
node/tools/src/rpc/server.rs

This PR adds typos checker into CI and fixes all typos it has found.

Add typos checker

---

node/Cargo.lock
node/Cargo.toml
node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/replica/leader_commit.rs
node/actors/bft/src/replica/leader_prepare.rs
node/actors/network/src/consensus/handshake/mod.rs
node/actors/sync_blocks/src/peers/events.rs
node/deny.toml
node/libs/concurrency/src/testonly.rs
node/libs/crypto/src/bn254/error.rs
node/libs/crypto/src/bn254/mod.rs
node/libs/crypto/src/bn254/tests.rs
node/libs/roles/src/validator/keys/aggregate_signature.rs
node/libs/roles/src/validator/keys/mod.rs
node/libs/roles/src/validator/keys/signature.rs
node/libs/roles/src/validator/messages/leader_commit.rs
node/libs/roles/src/validator/messages/leader_prepare.rs
node/libs/roles/src/validator/messages/msg.rs

Added checks for the validity of our BLS public keys as recommended by this [spec](https://www.ietf.org/archive/id/draft-irtf-cfrg-bls-signature-05.html). Namely we check that the public key is not zero and that it is in the correct subgroup.
We do it redundantly in two places (when we decode a public key and when we verify a signature).
Invalid public keys are a security risk.

Adds validity checks to BLS public keys

---

node/libs/protobuf/src/serde.rs

Allowing to use unknown fields during deserialization
It allows us to parse config schemas even if the config value is unknown

feat(protobuf): Allow unknown fields during serialization

---

node/actors/executor/src/lib.rs
node/actors/network/src/config.rs
node/actors/network/src/consensus/handshake/mod.rs
node/actors/network/src/consensus/handshake/tests.rs
node/actors/network/src/consensus/tests.rs
node/actors/network/src/gossip/handshake/mod.rs
node/actors/network/src/gossip/handshake/tests.rs
node/actors/network/src/gossip/tests.rs
node/actors/network/src/lib.rs
node/actors/network/src/metrics.rs
node/actors/network/src/mux/handshake.rs
node/actors/network/src/mux/mod.rs
node/actors/network/src/mux/tests/mod.rs
node/actors/network/src/preface.rs
node/actors/network/src/testonly.rs
node/libs/concurrency/src/limiter/mod.rs
node/libs/protobuf/src/proto_fmt.rs

Applied rate limiting to accepting inbound connections.
Added verification of encryption protocol to preface.
Removed `ProtoFmt::max_size()`.
Renamed `Stream::listen` to canonical `Stream::accept`.

Minor fixes to the network actor

---

node/Cargo.lock
node/Cargo.toml
node/deny.toml

Updates the revision of the `vise` crates.
Necessary to define newly added [`Info` metrics](https://matter-labs.github.io/vise/vise/struct.Info.html) in the main repo.

Bump revision of `vise` crates

---

node/actors/bft/src/lib.rs
node/libs/roles/src/validator/messages/consensus.rs
node/libs/roles/src/validator/messages/mod.rs
node/libs/roles/src/validator/messages/tests.rs
node/libs/roles/src/validator/testonly.rs
node/libs/roles/src/validator/tests.rs

Recent change of hash_to_point implementation is not backward compatible. I've bumped the protocol version and added tests so that in the future we won't introduce backward incompatible protocol changes to the crypto logic by accident. We are about to introduce several more backward incompatible changes, and they will also be included into the protocol version 1.

Bumped protocol version

---

node/actors/network/src/consensus/mod.rs
node/actors/network/src/consensus/tests.rs
node/actors/network/src/gossip/runner.rs
node/actors/network/src/lib.rs
node/actors/network/src/rpc/mod.rs
node/actors/network/src/testonly.rs
node/libs/crypto/src/ed25519/tests.rs
node/libs/roles/src/validator/messages/msg.rs

Implemented retransmission of consensus messages after reconnect. It should improve chances of finalizing blocks over a faulty network.

retransmission of consensus messages after reconnect

---

node/actors/sync_blocks/Cargo.toml
node/actors/sync_blocks/src/peers/mod.rs
node/actors/sync_blocks/src/peers/tests/mod.rs
node/actors/sync_blocks/src/peers/tests/multiple_peers.rs

It should improve the throughput between EN and main node. Rate limiting is still enforced by the network actor. This is a temporary fix, proper fix will require rewriting the sync_blocks actor.

removed limiting from sync_blocks

---

node/.config/nextest.toml
node/actors/bft/src/replica/block.rs
node/actors/bft/src/replica/leader_prepare.rs
node/actors/bft/src/replica/tests.rs
node/actors/bft/src/testonly/run.rs
node/actors/executor/src/tests.rs
node/actors/network/src/gossip/runner.rs
node/actors/network/src/lib.rs
node/actors/sync_blocks/src/peers/mod.rs
node/actors/sync_blocks/src/tests/end_to_end.rs
node/libs/concurrency/src/net/mod.rs
node/libs/storage/src/block_store/metrics.rs
node/libs/storage/src/block_store/mod.rs
node/libs/storage/src/testonly/in_memory.rs
node/libs/storage/src/testonly/mod.rs
node/libs/storage/src/tests.rs
node/tools/src/rpc/methods/last_committed_block.rs
node/tools/src/rpc/methods/last_view.rs
node/tools/src/store.rs
node/tools/src/tests.rs

Statekeeper is storing blocks to postgres in parallel to processing next blocks. Our simplified API so far required persisting one block to finish before processing the next block. This effectively disabled the parallelization in statekeeper and therefore the EN with consensus enabled was significantly slower than EN without consensus. This PR updates the api to allow persisting multiple blocks in parallel. Long term this change most likely won't be that useful, because statekeeper of a validator node will have to work synchronously with consensus (but that requires improving statekeeper anyway).
I've also implemented caching inmemory the most recent blocks (even if they got persisted) to address the inefficiency found during the loadtest.

Added support for persisting blocks in parallel

---

node/tools/src/bin/localnet_config.rs
node/tools/src/main.rs

This PR fixes `bft-450` issue. The PR sets 0700 and 0600 permissions to prevent the leaking of sensitive data to a local attacker.

Fix bft-450: file permissions

---

node/libs/roles/src/validator/testonly.rs

Added more flexibility in constructing `validator::testonly::Setup` for zksync-era tests.

Adjusted testonly utils

---

node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/replica/tests.rs
node/actors/bft/src/testonly/ut_harness.rs
node/libs/roles/src/validator/messages/leader_commit.rs
node/libs/roles/src/validator/messages/leader_prepare.rs
node/libs/roles/src/validator/messages/tests.rs
node/libs/roles/src/validator/testonly.rs
node/libs/roles/src/validator/tests.rs

Refactored the code to return errors on `PrepareQC::add` and `CommitQC::add`. We were just ignoring messages from different views, or signed by replicas not in the committee, or signed twice. Now these scenarios return an error.
From a code review it was suggested to return errors in `PrepareQC::add` and `CommitQC::add` instead of ignoring the message. FWIW, these cases are already been checked by our current caller, but for correctness we believe these functions should provide proper errors in case addition to the QC is not performed.

Return Result<(), Error> on QC add 

---

node/libs/roles/src/proto/validator.proto

When changing the crypto keys back from bn254 to bls12_381, we forgot to rename the proto fields as well. It is not feasible to do it now, because of backward compatibility, so I've just added comments to explain the discrepancy.

Added comment explaining discrepancy in the field names.

---

.github/workflows/protobuf.yaml
node/Cargo.lock
node/actors/bft/src/leader/state_machine.rs
node/actors/executor/src/lib.rs
node/actors/executor/src/tests.rs
node/actors/network/src/mux/transient_stream.rs
node/libs/concurrency/src/ctx/mod.rs
node/libs/concurrency/src/scope/mod.rs
node/libs/protobuf/src/std_conv.rs
node/tools/src/config.rs

We need to be able to configure a node to be a validator BEFORE it is added to the validator committee so that there is no downtime.

Enabled support for inactive validators.

---

node/libs/roles/src/proto/validator.proto
node/libs/roles/src/validator/conv.rs
node/libs/roles/src/validator/messages/consensus.rs
node/libs/roles/src/validator/messages/tests.rs
node/libs/roles/src/validator/testonly.rs
node/libs/roles/src/validator/tests.rs
node/tools/src/tests.rs

Adds a `LeaderSelectionMode::Rota` to allow specifying leaders in subsequent views using a list of public keys. The 1st validator on the list is going to be the leader in view 0, the 2nd in view 1, the 3rd in view 2, wrapping around to start from the beginning as the views increase. There can be repeated keys on the list, and they all have to be part of the committee. 
This is part of BFT-439 to modify the BFT tests to use the approach outlined in the [Twins paper](https://arxiv.org/abs/2004.10617). Part of that is the ability to control who is the leader in each of the views. 
With this change we should be able to generate a fixed leader schedule for the first few rounds of a protocol. The implementation wraps around so it's a total function, but in practice the tests will provide …

BFT-463: Add LeaderSelectionMode::Rota

---

node/libs/roles/src/validator/messages/leader_prepare.rs
node/libs/roles/src/validator/tests.rs

Now if there are >1 subquorums in the PrepareQC, leader will create a new proposal and replicas will require a new proposal.
It is possible to have 2 subquorums: vote A and vote B, each with >2f weight, in a single PrepareQC (even in the unweighted case, because QC contains n-f signatures, not 4f+1). In such a situation from the POV of the BFT algorithm, leader is eligible to do any of the following:
- reproposal for A
- reproposal for B
- a new proposal
Since the choice here is ambiguous, this can break liveness.

Fix ambiguous reproposal bug (BFT-454)

---

node/actors/bft/src/leader/replica_commit.rs
node/actors/bft/src/leader/replica_prepare.rs
node/actors/bft/src/leader/state_machine.rs
node/actors/bft/src/lib.rs
node/actors/bft/src/replica/block.rs
node/actors/bft/src/replica/mod.rs
node/actors/bft/src/replica/new_view.rs
node/actors/bft/src/replica/replica_prepare.rs
node/actors/bft/src/replica/state_machine.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/rpc/push_batch_votes.rs
node/libs/roles/src/attester/conv.rs
node/libs/roles/src/attester/keys/aggregate_signature.rs
node/libs/roles/src/attester/keys/signature.rs
node/libs/roles/src/attester/messages/batch.rs
node/libs/roles/src/attester/messages/msg.rs
node/libs/roles/src/attester/mod.rs
node/libs/roles/src/attester/tests.rs
node/libs/roles/src/validator/conv.rs
node/libs/roles/src/validator/messages/tests.rs
node/libs/roles/src/validator/testonly.rs

We now broadcast the Replica Prepare message to all replicas. Replicas then use it to update their high Commit QCs and change views id necessary.
The high Commit QC broadcast should be independent from the rest of the algorithm, so that view synchronization is independent from the bft logic - it simplifies reasoning a lot and prevents potential deadlocks that our implementation currently has

Make validators broadcast the high Commit QC (BFT-458)

---

node/actors/bft/src/testonly/node.rs
node/actors/bft/src/testonly/run.rs
node/actors/bft/src/tests.rs
node/actors/network/src/gossip/fetch.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/gossip/runner.rs
node/actors/network/src/testonly.rs
node/libs/utils/src/pipe.rs

Add tests that run multiple Twins scenarios with random number of replicas as twins.
```shell
cargo nextest run -p zksync_consensus_bft twins_network --no-capture
```
Initially the test failed when partitions are introduced. I'll try to understand if this is because the leader got isolated and an important message got lost. Would like to understand if eventual delivery is an absolute requirement even if all partitions are at least as large as the quorum size.
🔍  I think the reason for the test failing is because it looks for all nodes having persisted a certain number of blocks, but if a proposal with the payload is missed due to a partition preventing the message from being delivered, then there is no mechanism in the machinery instantiated by the test to procure these later, and those …

BFT-465: Twins tests

---

node/actors/bft/src/leader/state_machine.rs
node/actors/bft/src/replica/leader_prepare.rs
node/actors/bft/src/replica/state_machine.rs
node/actors/bft/src/testonly/run.rs
node/actors/bft/src/tests.rs

To deal with the loss of liveness caused by multiple leaders who owned both the payload and the CommitQC going down, and further replicas stop participating in consensus until they have the previous payload which never comes.

BFT-466: LeaderPrepare wait for previous block deadlock

---

node/Cargo.lock
node/actors/bft/Cargo.toml
node/actors/bft/src/testonly/run.rs
node/actors/bft/src/tests.rs

Some of the tests were flaky because of cpu contention affecting interleavings. This fix makes the passing time (almost) deterministic, by the use of `tokio::time::pause()`. The other consequence is that runtime used in multiple tests has been changed from multi-threaded to single-threaded. This also helps the determinism because the nextest parallelism is bounded by the number of cores - if we make all tests single-threaded, behavior of the test will be the same when executed separately and in a test suite.
Also converted a should_panic test to regular test for consistency.
Tuned size of some of the tests to reasonable execution times.

made tests more deterministic

---

.github/workflows/spec.yaml

Fixes invalid syntax in `spec.yaml`
I don't know why it didn't fail on `main` but on my PR after merging `main` into it CI complained about `spec.yaml` having no workflow due to invalid syntax.

FIX: Add missing colon to spec.yaml

---

node/libs/storage/src/batch_store.rs
node/libs/storage/src/testonly/in_memory.rs
node/libs/storage/src/testonly/mod.rs

Change the methods of `PersistentBatchStore` to be `async`.
Because I want to implement them in the `zksync-era` repo and the DAL methods are async.

BFT-476: Change PersistentBatchStore methods to async

---

node/libs/storage/src/batch_store.rs
node/libs/storage/src/testonly/in_memory.rs
node/libs/storage/src/testonly/mod.rs

Adds the `ctx` parameter to the methods of `PersistentBatchStore` and changes the return type to `ctx::Result`.
Need them to implement the trait in https://github.com/matter-labs/zksync-era/pull/2340

BFT-476: Add ctx to PersistentBatchStore methods

---

node/Cargo.lock
node/Cargo.toml
node/actors/bft/Cargo.toml
node/actors/executor/Cargo.toml
node/actors/network/Cargo.toml
node/libs/concurrency/Cargo.toml
node/libs/crypto/Cargo.toml
node/libs/protobuf/Cargo.toml
node/libs/protobuf_build/Cargo.toml
node/libs/roles/Cargo.toml
node/libs/storage/Cargo.toml
node/libs/utils/Cargo.toml
node/tests/Cargo.toml
node/tools/Cargo.toml

- Changes git dependency on `pairing` to the published one.
- Same for `vise` and `vise-exporter`
- Uses `workspace.version` for all the crates.

chore: Prepare crates for publishing

---

node/Cargo.lock
node/Cargo.toml
node/actors/bft/Cargo.toml
node/actors/executor/Cargo.toml
node/actors/network/Cargo.toml
node/libs/concurrency/Cargo.toml
node/libs/crypto/Cargo.toml
node/libs/protobuf/Cargo.toml
node/libs/protobuf_build/Cargo.toml
node/libs/roles/Cargo.toml
node/libs/storage/Cargo.toml
node/libs/utils/Cargo.toml
node/tests/Cargo.toml
node/tools/Cargo.toml

- Changes version to `0.1.0-rc.1` since the codebase is under heavy changes and is not in production yet; will prevent us from premature version bumps until consensus is on mainnet.
- Sets other required fields for publishing.
- Marks tests as `publish=false`.
Preparations for publishing on crates.io.

chore: Misc preparations for publishing

---

spec/informal-spec/replica.rs
spec/informal-spec/types.rs

Refactored (in the informal spec) `TimeoutQC`, `SignedTimeoutVote` and `TimeoutVote` so that `TimeoutQC` contains only one `CommitQC` (the high QC).
It reduces the state space which should help with model checking.

Refactored TimeoutQC to contain just one CommitQC

---

node/actors/network/src/gossip/batch_votes.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/gossip/runner.rs
node/actors/network/src/gossip/tests/mod.rs
node/actors/network/src/lib.rs
node/actors/network/src/tests.rs
node/libs/roles/src/attester/conv.rs
node/libs/roles/src/attester/keys/secret_key.rs
node/libs/roles/src/attester/messages/batch.rs
node/libs/roles/src/attester/messages/msg.rs
node/libs/roles/src/attester/testonly.rs
node/libs/roles/src/attester/tests.rs
node/libs/roles/src/proto/attester.proto
node/libs/roles/src/validator/messages/consensus.rs
node/libs/storage/src/batch_store.rs
node/libs/storage/src/testonly/mod.rs

`BatchVotes` still only allows 1 vote per attester and thus doesn't fully handle multiple outstanding L1 batches. That will come later when we'll have subscribed to notifications about the highest finalised batch number, coming from the main node API which doesn't exist yet. That will serve as our beacon for what kind of ranges of votes to accept. Currently for defensive reasons we only accept one vote per attester, which means if attesters keep voting on different heights, always out of sync with each other, they might never form a quorum. That is considered okay at this point; we save what we can and see how it works. 1 minute batches should be long enough not to cause trouble for gossip.
With these changes the node will react to votes coming in over gossip and forming a quorum over the …

feat: Collect votes for batch QC and save into store (BFT-477)

---

node/Cargo.lock
node/actors/executor/src/attestation.rs
node/actors/executor/src/lib.rs
node/libs/roles/src/attester/messages/batch.rs
node/libs/storage/Cargo.toml
node/libs/storage/src/batch_store.rs
node/libs/storage/src/testonly/in_memory.rs

The code will re-submit the node's signature after a restart to a number of batches to be determined by the database query. We can say we'll re-publish the top 10 unsigned batches, or we can say we'll only look for the ones which follow the last finalised batch observed the Main node. It is enough to publish a vote once because of the way `BatchVotes` works (gossip peers will pull the data they need when they connect). Because we'll always have the batches in order, we can take note of the highest number we have published a vote for and never publish it again (until a restart), to save ourselves the trouble of repeatedly retrieving and signing the payload. That said it is assumed that `batch_to_sign` is cheap as it just needs to look up a hash in the DB.
The ticket will need a counterpart …

feat: Batch vote publish loop (BFT-474)

---

node/Cargo.lock
node/Cargo.toml
node/actors/bft/Cargo.toml
node/actors/executor/Cargo.toml
node/actors/network/Cargo.toml
node/deny.toml
node/libs/concurrency/Cargo.toml
node/libs/crypto/Cargo.toml
node/libs/protobuf/Cargo.toml
node/libs/protobuf_build/Cargo.toml
node/libs/roles/Cargo.toml
node/libs/storage/Cargo.toml
node/libs/utils/Cargo.toml
node/tools/Cargo.toml

Prepares the first release for consensus codebase (already on crates.io)
I had to bump `tls-listener` and `tokio-rustls`, because otherwise network actor won't compile outside of workspace.
Publishing crates on crates.io

Prepare 0.1.0-rc.1 release

---

node/Cargo.lock
node/Cargo.toml

Bumps the version to 0.1.0-rc.2
So that we can merge https://github.com/matter-labs/zksync-era/pull/2399 and https://github.com/matter-labs/zksync-era/pull/2410

CHORE: Update version to 0.1.0-rc.2

---

node/actors/executor/src/attestation.rs
node/libs/roles/src/attester/messages/batch.rs
node/libs/storage/src/batch_store.rs

* Fixes the comments I made about `SyncBatch::proof` requiring L1 inclusion - that was based on a misunderstanding that the `proof` was a Merkle proof starting from the L1 state root hash, rather than a field inside the zksync system contract on L1. We only need an L1 client to validate the proof, but we can produce it offline as soon as we have the commitment locally.
* Changed the loop in `AttesterRunner` so that it waits for `persisted` state of the `BatchStore` to indicate that the next batch number is available. This will be when the `SyncBatch` can be constructed, so it's when the commitment is ready too (or will be, not currently) and we're ready to sign the payload. 
* Removed `BatchStore::last_batch_number`; I wanted to use `persisted.last`, which can be `None` in the beginning …

fix: Comments about SyncBatch vs L1 and wait for batch persisted (BFT-474)

---

node/actors/executor/src/lib.rs

Adds more logging around attestations. 
For some reason on stage2 the main node doesn't seem to have the attester key, even though it's in the config.

DEBUG: Log if the node is not an attester

---

node/Cargo.lock
node/Cargo.toml

Bumps the version to 0.1.0-rc.4 for a new release.
So that I can deploy the batch vote gossip metrics and add some of them to the Grafana dashboards (need to bump the era-consensus version in zksync-era).

Bump version to 0.1.0-rc.4

---

node/actors/network/src/consensus/handshake/mod.rs
node/actors/network/src/consensus/handshake/tests.rs
node/actors/network/src/consensus/tests.rs
node/actors/network/src/frame.rs
node/actors/network/src/gossip/handshake/mod.rs
node/actors/network/src/gossip/handshake/tests.rs
node/actors/network/src/gossip/tests/mod.rs
node/actors/network/src/lib.rs
node/actors/network/src/metrics.rs
node/actors/network/src/mux/mod.rs
node/actors/network/src/noise/stream.rs
node/actors/network/src/preface.rs

peer_addr() may fail if the network socket is closed. It needs to be handled gracefully.
I've also refactored some of the error handling to propagate cancellation better.

removed panicking when peer_addr fails

---

node/Cargo.lock
node/actors/bft/src/testonly/run.rs
node/actors/executor/Cargo.toml
node/actors/executor/src/attestation.rs
node/actors/executor/src/lib.rs
node/actors/executor/src/tests.rs
node/actors/network/src/consensus/tests.rs
node/actors/network/src/gossip/attestation_status.rs
node/actors/network/src/gossip/batch_votes.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/gossip/tests/mod.rs
node/actors/network/src/lib.rs
node/actors/network/src/testonly.rs
node/libs/storage/src/batch_store/metrics.rs
node/libs/storage/src/batch_store/mod.rs
node/libs/storage/src/testonly/in_memory.rs
node/tools/src/config.rs

Poll the main node for which batch height to vote on.
The `AttesterStatusRunner` polls the API at fixed intervals without any exponential backoff. I thought 5s would be a reasonable default value. With 60s batches this seems fine because the *next* batch to sign will be signalled as soon as the current batch QC is inserted into the database, which is well ahead of time of when  the next batch and its commitment will be available. If we think we'll need to catch up with historical batch signatures it might be a bit slow. We generally still have to account for gossiping around the votes though, which in a large enough network could be on the order of several seconds as well.
There is a pathological sequence of events that could prevent the feature from starting on a fresh database with no …

feat: Poll the main node for batch to vote on (BFT-496)

---

node/actors/executor/src/attestation.rs
node/actors/executor/src/tests.rs
node/actors/network/src/gossip/attestation_status.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/gossip/tests/fetch_blocks.rs
node/actors/network/src/testonly.rs
node/tools/src/config.rs

`AttestationStatusWatch` must be initialised with a `BatchNumber`, it cannot have `None` any more. `AttestationStatusRunner::new` was replaced with the `AttestationStatusRunner::init` method which asynchronously polls the API until the first value is returned, and then returns itself along with the `AttestationStatusWatch` it created. This can then be passed to the `Executor`, while the `AttestationStatusRunner::run` will keep the status up to date in the background.
In the review of https://github.com/matter-labs/era-consensus/pull/161 it was observed that the `Executor` can wait until this data is available. In theory it is only unavailable if the main node API is down, in which case an external node couldn't pull Genesis either and would probably fail during startup, or if the Genesis …

improve: AttestationStatusWatch::next_batch_to_attest non-optional (BFT-496)

---

node/actors/executor/src/attestation.rs
node/actors/executor/src/tests.rs

Fixes `AttestationStatusRunner::poll_until_some` to return after a successful poll. Originally it returned a value, then decided to write it into the field and forgot to add a return statement.
Tests in https://github.com/matter-labs/zksync-era/pull/2544 time out because the initialisation never completes and the `Executor` is never started.

fix: AttestationStatusRunner::poll_until_some return after success (BFT-496)

---

node/Cargo.lock
node/deny.toml

Changes the config of cargo deny because a breaking version of deny was published.

Fixed cargo deny config

---

node/actors/executor/src/attestation.rs
node/actors/executor/src/tests.rs
node/actors/network/src/gossip/attestation_status.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/testonly.rs

`AttestationRunner::init` should not try to initialise the `AttestationStatus` from the API. Let it be `None` and do the init in the background.
This is partially undoing what https://github.com/matter-labs/era-consensus/pull/165 did.
The rollout procedure to mainnet was that the EN goes first, then the main node. The EN cannot start without the main node API.

improve: Do not initialise the AttestationStatus (BFT-496)

---

node/Cargo.lock
node/Cargo.toml

Bumps the version to `0.1.0-rc.6`
So that we can release https://github.com/matter-labs/era-consensus/pull/170 and https://github.com/matter-labs/era-consensus/pull/169 to make zksync-era backwards compatible.

Bump version to 0.1.0-rc.6

---

node/actors/bft/src/testonly/twins/partition.rs
node/actors/executor/src/tests.rs
node/actors/network/src/gossip/attestation_status.rs
node/actors/network/src/gossip/mod.rs
node/actors/network/src/mux/mod.rs
node/actors/network/src/noise/stream.rs
node/actors/network/src/rpc/push_batch_votes.rs
node/actors/network/src/rpc/tests.rs
node/libs/concurrency/src/ctx/channel.rs
node/libs/concurrency/src/sync/prunable_mpsc/mod.rs
node/libs/protobuf_build/src/lib.rs

We added an extra field to the Batch message, without considering the fact that an extra field won't be recognized by old binaries and they will fail to verify signatures on Batch messages. They will consider sending such invalid signatures malicious and will disconnect from the peer. To avoid this we create a new RPC instead (by just bumping the capability id on push_batch_votes RPC) which will not be interpreted by the old binaries at all.

bumped capability ID of the push_batch_votes rpc

---

node/Cargo.lock
node/Cargo.toml

`vise` 0.1.0 has compilation issues on modern nightly because of `linkme` crates, so the new version was migrated to use `ctor` instead.
Unblock the path to using modern nightly Rust.

chore: Bump vise & release rc.9

---

node/actors/network/src/lib.rs

It was removed by accident during the instrumentation refactor.
The span name is intentionally short, so that the logs don't become too verbose

Reintroduced the lost span

---

node/Cargo.lock
node/Cargo.toml
node/libs/crypto/Cargo.toml

- Removes `pairing` dependency.
- Needless dep.
- Marked as `feat` to test release-please.

feat: Remove pairing crate dependency

---

node/Cargo.lock
node/libs/protobuf/examples/conformance_test/main.rs
node/libs/protobuf/src/serde.rs
node/libs/protobuf/src/testonly/mod.rs
node/tools/src/bin/localnet_config.rs
node/tools/src/config.rs
node/tools/src/k8s.rs
node/tools/src/main.rs

It turned out to be too easy to use it incorrectly with an implicit default.

refactor: explicit deny_unknown_fields for protobuf serde deserialization

---

.github/workflows/protobuf_conformance.yaml
node/Cargo.lock
node/Cargo.toml
node/components/bft/src/chonky_bft/mod.rs
node/components/bft/src/chonky_bft/new_view.rs
node/components/bft/src/chonky_bft/proposal.rs
node/components/bft/src/chonky_bft/proposer.rs
node/components/bft/src/chonky_bft/testonly.rs
node/components/bft/src/chonky_bft/tests/timeout.rs
node/components/bft/src/chonky_bft/timeout.rs
node/components/bft/src/metrics.rs
node/components/bft/src/testonly/node.rs
node/components/bft/src/testonly/twins/scenario.rs
node/components/network/src/gossip/loadtest/mod.rs
node/components/network/src/testonly.rs
node/libs/concurrency/src/limiter/mod.rs
node/libs/roles/src/validator/messages/replica_commit.rs
node/libs/roles/src/validator/messages/tests/versions.rs

Custom Ord implementation was causing timeout votes with different high qc (with the same view) to be deduplicated, which invalidated the aggregated signature. I've added a test for this case, and preemptively removed all custom Ord implementations on messages.

fix: TimeoutQC aggregation

---

node/components/bft/src/chonky_bft/mod.rs
node/components/bft/src/chonky_bft/new_view.rs
node/components/bft/src/chonky_bft/proposer.rs
node/components/bft/src/chonky_bft/testonly.rs
node/components/bft/src/config.rs
node/components/bft/src/testonly/node.rs
node/components/executor/src/lib.rs
node/components/executor/src/tests.rs
node/tools/build.rs
node/tools/src/bin/deployer.rs
node/tools/src/bin/localnet_config.rs
node/tools/src/config.rs
node/tools/src/proto/mod.proto
node/tools/src/tests.rs

The hardcoded 2s view timeout was causing problems in Era testnet because the block time there is longer (>5s). View timeout needs to be a configurable parameter since different chains will want different block times.

feat: Added view timeout duration as a config parameter

---

infrastructure/loadtests/ansible/playbook.yml
node/components/bft/src/chonky_bft/new_view.rs
node/components/bft/src/chonky_bft/testonly.rs
node/components/bft/src/chonky_bft/tests/new_view.rs
node/components/bft/src/testonly/node.rs
node/components/network/src/config.rs
node/components/network/src/consensus/mod.rs
node/libs/concurrency/src/ctx/clock.rs
node/libs/storage/src/testonly/in_memory.rs
node/tools/src/bin/localnet_config.rs
node/tools/src/config.rs
node/tools/src/main.rs

Removed verification of redundant NewView messages.
Fixed incompatibility between zksync_conncurrency and `tokio::time::pause()`.
Added in-memory mode to the test node binary.
Fixed `payload_size` flag in the test node binary.
Removed obsolete rate limits from the network config.

feat: loadtest improvements

---

node/components/bft/src/chonky_bft/block.rs
node/components/bft/src/chonky_bft/commit.rs
node/components/bft/src/chonky_bft/mod.rs
node/components/bft/src/chonky_bft/new_view.rs
node/components/bft/src/chonky_bft/proposal.rs
node/components/bft/src/chonky_bft/proposer.rs
node/components/bft/src/chonky_bft/testonly.rs
node/components/bft/src/chonky_bft/timeout.rs
node/components/bft/src/lib.rs
node/components/bft/src/testonly/run.rs
spec/informal-spec/README.md
spec/informal-spec/replica.rs

- Fixes issue with replicas not sending timeouts/new views after restarting.
- Adds more logs for better visibility.
From Slack: 
> I've deployed ChonkyBFT with multiple (3) validators on stage two weeks ago and it has halted a few times, always requiring a regenesis (basically a hard fork) to restart it.
> Here's the issue. Right now, when we send a message it is added to a queue in our network component. There the component retries sending the message until it succeeds. That's basically what we describe in network model [here](https://github.com/matter-labs/era-consensus/tree/main/spec/informal-spec). The problem though is that when a node is restarted it loses that queue of messages it is trying to send. The only data we persist is …

fix: Replicas forget messages and halt on restart

---

.github/workflows/publish-crates.yaml
.github/workflows/release-please.yaml

ci: add manual workflow for crates.io publishing

---

.github/workflows/publish-crates.yaml
node/Cargo.toml

To fix crates.io publishing and builds.

ci: fix workspace path in publish crates

---

.github/workflows/protobuf.yaml
.github/workflows/protobuf_conformance.yaml
.github/workflows/rust.yml

CI in `main` started to fail:
https://github.com/matter-labs/era-consensus/actions/runs/14491488072/job/40648760180
```
error: process didn't exit successfully: `sccache /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -vV` (exit status: 2)
--- stderr
sccache: error: Server startup failed: cache storage failed to read: Unexpected (permanent) at read => {"$id":"1","innerException":null,"message":"This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset","typeName":"Microsoft.Azure.DevOps.ArtifactCache.WebApi.ArtifactCacheServiceDecommissionedException, Microsoft.Azure.DevOps.ArtifactCache.WebApi","typeKey":"ArtifactCacheServiceDecommissionedException","errorCode":0,"eventId" …
```

ci: fix sccache action issues

---

node/components/executor/src/lib.rs
node/components/network/src/debug_page/mod.rs

Debug server was being stopped for port reuse. This allows port reuse but it's only a quick solution as it won't let us see the debug page properly while we have several network instances running in parallel.

feat: fix debug page port reuse
